import { createContext, useContext, useEffect, useMemo, useState } from 'react';

const STORAGE_KEY = 'hajj_language';
const LANGUAGES = [
  { code: 'en', label: 'English', shortLabel: 'EN' },
  { code: 'fr', label: 'Français', shortLabel: 'FR' },
  { code: 'ar', label: 'العربية', shortLabel: 'AR' },
];

const MESSAGES = {
  en: {
    dashboard: 'Dashboard',
    overview: 'Overview',
    agencies: 'Agencies',
    dossiers: 'Applications',
    pilgrims: 'Pilgrims',
    notifications: 'Notifications',
    payments: 'Payments',
    documents: 'Documents',
    groups: 'Groups',
    guides: 'Guides',
    travel: 'Trips',
    presence: 'QR & Presence',
    logout: 'Log out',
    language: 'Language',
    welcome: 'Welcome',
    connected: 'Your account is connected to the backend.',
    myApplications: 'My applications',
    noApplications: 'No application yet.',
    loading: 'Loading...',
    allApplications: 'All applications',
    allAgencies: 'All agencies',
    registeredAgencies: 'Registered agencies',
    registeredPilgrims: 'Registered pilgrims',
    activeApplications: 'Active applications',
    noData: 'No data available yet.',
    search: 'Search',
    encadreurs: 'Guides',
    profile: 'Profile',
    operations: 'Operations',
    loginKicker: 'Pilgrimage management',
    loginSubtitle: 'Sign in to access your workspace.',
    emailField: 'Email',
    passwordField: 'Password',
    signIn: 'Sign in',
    signingIn: 'Signing in…',
    newPilgrim: 'New pilgrim?',
    createAccount: 'Create an account',
    emailRequired: 'Email is required.',
    invalidEmail: 'Enter a valid email address.',
    passwordRequired: 'Password is required.',
    invalidCredentials: 'Incorrect email or password.',
    loginError: 'Something went wrong. Please try again.',
    roleAdmin: 'Administrator',
    roleAgency: 'Agency manager',
    roleGuide: 'Guide',
    rolePilgrim: 'Pilgrim',
  },
  fr: {
    dashboard: 'Tableau de bord',
    overview: "Vue d'ensemble",
    agencies: 'Agences',
    dossiers: 'Dossiers',
    pilgrims: 'Pèlerins',
    notifications: 'Notifications',
    payments: 'Paiements',
    documents: 'Documents',
    groups: 'Groupes',
    guides: 'Guides',
    travel: 'Voyages',
    presence: 'QR & Présence',
    logout: 'Déconnexion',
    language: 'Langue',
    welcome: 'Bienvenue',
    connected: 'Ton compte est connecté au backend.',
    myApplications: 'Mes dossiers',
    noApplications: 'Aucun dossier pour le moment.',
    loading: 'Chargement…',
    allApplications: 'Tous les dossiers',
    allAgencies: 'Toutes les agences',
    registeredAgencies: 'Agences enregistrées',
    registeredPilgrims: 'Pèlerins inscrits',
    activeApplications: 'Dossiers actifs',
    noData: 'Aucune donnée disponible pour le moment.',
    search: 'Rechercher',
    encadreurs: 'Encadreurs',
    profile: 'Profil',
    operations: 'Opérations',
    loginKicker: 'Gestion du pèlerinage',
    loginSubtitle: 'Connecte-toi pour accéder à ton espace.',
    emailField: 'Email',
    passwordField: 'Mot de passe',
    signIn: 'Se connecter',
    signingIn: 'Connexion…',
    newPilgrim: 'Nouveau pèlerin ?',
    createAccount: 'Créer un compte',
    emailRequired: "L'email est requis.",
    invalidEmail: "Format d'email invalide.",
    passwordRequired: 'Le mot de passe est requis.',
    invalidCredentials: 'Email ou mot de passe incorrect.',
    loginError: 'Une erreur est survenue. Réessaie.',
    roleAdmin: 'Administrateur',
    roleAgency: 'Responsable d’agence',
    roleGuide: 'Guide',
    rolePilgrim: 'Pèlerin',
  },
  ar: {
    dashboard: 'لوحة التحكم',
    overview: 'نظرة عامة',
    agencies: 'الوكالات',
    dossiers: 'الملفات',
    pilgrims: 'الحجاج',
    notifications: 'الإشعارات',
    payments: 'المدفوعات',
    documents: 'الوثائق',
    groups: 'المجموعات',
    guides: 'المرشدون',
    travel: 'الرحلات',
    presence: 'QR والحضور',
    logout: 'تسجيل الخروج',
    language: 'اللغة',
    welcome: 'مرحباً',
    connected: 'حسابك متصل بالخادم.',
    myApplications: 'ملفاتي',
    noApplications: 'لا يوجد ملف حتى الآن.',
    loading: 'جار التحميل...',
    allApplications: 'كل الملفات',
    allAgencies: 'كل الوكالات',
    registeredAgencies: 'الوكالات المسجلة',
    registeredPilgrims: 'الحجاج المسجلون',
    activeApplications: 'الملفات النشطة',
    noData: 'لا توجد بيانات متاحة حالياً.',
    search: 'بحث',
    encadreurs: 'المرشدون',
    profile: 'الملف الشخصي',
    operations: 'العمليات',
    loginKicker: 'إدارة الحج',
    loginSubtitle: 'سجّل الدخول للوصول إلى حسابك.',
    emailField: 'البريد الإلكتروني',
    passwordField: 'كلمة المرور',
    signIn: 'تسجيل الدخول',
    signingIn: 'جارٍ تسجيل الدخول…',
    newPilgrim: 'حاج جديد؟',
    createAccount: 'إنشاء حساب',
    emailRequired: 'البريد الإلكتروني مطلوب.',
    invalidEmail: 'أدخل عنوان بريد إلكتروني صالحاً.',
    passwordRequired: 'كلمة المرور مطلوبة.',
    invalidCredentials: 'البريد الإلكتروني أو كلمة المرور غير صحيحة.',
    loginError: 'حدث خطأ. حاول مرة أخرى.',
    roleAdmin: 'مسؤول النظام',
    roleAgency: 'مسؤول الوكالة',
    roleGuide: 'مرشد',
    rolePilgrim: 'حاج',
  },
};

const LanguageContext = createContext(null);

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState(() => localStorage.getItem(STORAGE_KEY) || 'en');

  useEffect(() => {
    const selected = LANGUAGES.some((item) => item.code === language) ? language : 'en';
    localStorage.setItem(STORAGE_KEY, selected);
    document.documentElement.lang = selected;
    document.documentElement.dir = selected === 'ar' ? 'rtl' : 'ltr';
  }, [language]);

  const value = useMemo(() => ({
    language,
    languages: LANGUAGES,
    setLanguage,
    t: (key) => MESSAGES[language]?.[key] ?? MESSAGES.en[key] ?? key,
  }), [language]);

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) throw new Error('useLanguage doit être utilisé à l’intérieur de <LanguageProvider>.');
  return context;
}
