import { PAGE_TRANSLATIONS } from './translations.pages.js';
import { OPERATIONS_TRANSLATIONS } from './translations.operations.js';
import { ROLES_TRANSLATIONS } from './translations.roles.js';
import { LIVE_TRANSLATIONS } from './translations.live.js';
import { MOBILE_TRANSLATIONS } from './translations.mobile.js';
import { COURSES_TRANSLATIONS } from './translations.courses.js';
import { PILGRIM_TRANSLATIONS } from './translations.pilgrim.js';

export const LANGUAGES = Object.freeze([
  { code: 'en', label: 'English', shortLabel: 'EN' },
  { code: 'fr', label: 'Français', shortLabel: 'FR' },
  { code: 'ar', label: 'العربية', shortLabel: 'AR' },
]);

const BASE_TRANSLATIONS = Object.freeze({
  en: Object.freeze({
    dashboard: 'Dashboard', overview: 'Overview', agencies: 'Agencies', dossiers: 'Applications', pilgrims: 'Pilgrims', notifications: 'Notifications', payments: 'Payments', documents: 'Documents', groups: 'Groups', guides: 'Guides', travel: 'Trips', presence: 'QR & Attendance', statistics: 'Statistics', organisation: 'Organisation', settings: 'Settings', logout: 'Log out', language: 'Language', welcome: 'Welcome', connected: 'Your account is connected to the backend.', myApplications: 'My applications', noApplications: 'No application yet.', loading: 'Loading…', allApplications: 'All applications', allAgencies: 'All agencies', registeredAgencies: 'Registered agencies', registeredPilgrims: 'Registered pilgrims', activeApplications: 'Active applications', noData: 'No data available yet.', search: 'Search', encadreurs: 'Guides', profile: 'Profile', operations: 'Operations',
    loginKicker: 'Pilgrimage management', loginSubtitle: 'Sign in to access your workspace.', emailField: 'Email', passwordField: 'Password', signIn: 'Sign in', signingIn: 'Signing in…', newPilgrim: 'New pilgrim?', createAccount: 'Create an account', emailRequired: 'Email is required.', invalidEmail: 'Enter a valid email address.', passwordRequired: 'Password is required.', invalidCredentials: 'Incorrect email or password.', loginError: 'Something went wrong. Please try again.', registerTitle: 'Create an account', registerSubtitle: 'Enter your information to start your pilgrim file.', firstName: 'First name', lastName: 'Last name', phone: 'Phone', confirmPassword: 'Confirm password', register: 'Create my account', registering: 'Creating…', existingAccount: 'Already have an account?', duplicateEmail: 'This email is already in use.', registrationError: 'Unable to create the account.',
    roleAdmin: 'Administrator', roleAgency: 'Agency manager', roleGuide: 'Guide', rolePilgrim: 'Pilgrim', account: 'Account', manageAccount: 'Manage your personal information and password.', currentPassword: 'Current password', newPassword: 'New password', saveChanges: 'Save changes', saving: 'Saving…', profileUpdated: 'Profile updated successfully.', profileUpdateFailed: 'Unable to update your profile.',
    pilgrimageManagement: 'Pilgrimage management', allStatus: 'All statuses', noMatchingDossiers: 'No applications match these filters.', dossier: 'Application', pilgrim: 'Pilgrim', agency: 'Agency', createdAt: 'Created', documentsProgress: 'Documents', dossierDetails: 'Application details', dossierHistory: 'Application history', fullName: 'Full name', status: 'Status', rejectReason: 'Rejection reason', rejectConfirm: 'Confirm rejection', cancel: 'Cancel', validate: 'Approve', reject: 'Reject', returnToDossiers: 'Back to applications', searchDossiers: 'Search by name or number…', noDossierForAction: 'No applications need attention right now.',
    status_brouillon: 'Draft', status_soumis: 'Submitted', status_en_verification: 'Under review', status_valide: 'Approved', status_transmis_nusuk: 'Sent to Nusuk', status_confirme: 'Confirmed', status_rejete: 'Rejected', status_annule: 'Cancelled',
    statusPending: 'Pending', statusUnderReview: 'Under review', statusApproved: 'Approved', statusRejected: 'Rejected', statusExpired: 'Expired', statusAll: 'All statuses', statusToReview: 'Needs review', statusNewVersion: 'New version requested', reviewFinished: 'Review complete', takeForReview: 'Start review', requestNewVersion: 'Request new version', sendRequest: 'Send request', reasonToPilgrim: 'Reason sent to pilgrim', searchDocuments: 'Pilgrim, application, type or file…', uploadedAt: 'Uploaded', expiration: 'Expiration', review: 'Review', noDocumentsForFilter: 'No documents match this filter.', documentsToReview: '{{count}} need review', documentReviewTitle: 'Documents', documentReviewSubtitle: 'Review files and request a new version when needed.',
    season: 'Hajj season', createSeason: 'Create Hajj season', newSeason: 'New season', seasonLabel: 'Season name', seasonYear: 'Year', startDate: 'Start date', endDate: 'End date', seasonDescription: 'Description', activeSeason: 'Active season', active: 'Active', inactive: 'Inactive', createPackage: 'Create package', newPackage: 'New package', packageName: 'Package name', packageDescription: 'Description', packagePrice: 'Price', currency: 'Currency', includedServices: 'Included services', packageActive: 'Package active', seasonsPackages: 'Hajj seasons & packages', seasonTracking: 'Season, package and campaign payment tracking.', noSeasons: 'No seasons have been created.', noPackages: 'No packages have been created.', seasonsCount: 'Seasons', packagesCount: 'Packages', paymentCount: 'Payments', collectedAmount: 'Amount collected',
    organisationTitle: 'Organisations', organisationDescription: 'Each agency is managed as a MyHajj237 organisation.', organisationCount: '{{count}} organisations', allOrganisationStatuses: 'All statuses', organisationName: 'Organisation name', legalName: 'Legal name', registrationNumber: 'Registration number', country: 'Country', city: 'City', address: 'Address', logoUrl: 'Logo URL', subscriptionPlan: 'Subscription plan', subscriptionStatus: 'Subscription status', organisationStatus: 'Organisation status', organisationRecord: 'Registration', contact: 'Contact', subscription: 'Subscription', edit: 'Edit', editOrganisation: 'Edit organisation', organisationSaved: 'Organisation updated.', organisationLoadError: 'Unable to load organisations.', noOrganisationMatch: 'No organisation matches this search.', noRegistrationNumber: 'Registration number not provided', phoneNotProvided: 'Phone not provided', close: 'Close',
    groupManagementTitle: 'Groups', groupManagementDescription: 'Create groups, assign a guide and manage pilgrims.', groupCodeName: 'Code / name', assignedGuide: 'Guide', organisation: 'Organisation', members: 'Pilgrims', manage: 'Manage', createGroup: 'Create group', editGroup: 'Edit group', groupName: 'Group name', selectOrganisation: 'Select an organisation', noGuide: 'No guide assigned', guideNotAssigned: 'No guide assigned', seasonChangeWarning: 'Remove or move the pilgrims before changing the group season.', generatedCode: 'The code is generated from the season and group ID.', groupStats: 'Group statistics', pilgrimsAssigned: 'Pilgrims assigned', groupAverage: 'Average per group', noGroupsSeason: 'No groups for this season.', groupSaved: 'Group saved.', groupCreated: 'Group created.', groupUpdated: 'Group updated.', groupLoadError: 'Unable to load groups and guides.', groupSaveError: 'Unable to save the group.', viewPilgrims: 'Pilgrims', selectPilgrim: 'Select an unassigned pilgrim', addPilgrim: 'Add pilgrim', moveTo: 'Move to', action: 'Action', move: 'Move', remove: 'Remove', noPilgrimsGroup: 'No pilgrims in this group.', pilgrimAdded: 'Pilgrim added to the group.', pilgrimRemoved: 'Pilgrim removed from the group.', pilgrimMoved: 'Pilgrim moved to the target group.', addPilgrimError: 'Unable to add the pilgrim.', removePilgrimError: 'Unable to remove the pilgrim.', movePilgrimError: 'Unable to move the pilgrim.', loadMembersError: 'Unable to load group members.',
    chatDiscussion: 'Group discussion', backToGroups: 'Back to groups', noMessages: 'No messages yet. Send the first update to the group.', writeMessage: 'Write a message to the group…', attachMedia: 'Attach a photo, video or PDF', changeMedia: 'Choose another file', removeMedia: 'Remove media', mediaPreview: 'Preview before sending', send: 'Send', sending: 'Sending…', messageSendError: 'Unable to send the message. Please try again.', messagesLoadError: 'Unable to retrieve messages.', noGroupAccess: 'Group not found or access denied.',
    paymentManagement: 'Payments', paymentSubtitle: 'Payments, balances and Hajj settlement approvals.', registeredPayments: 'Payments recorded', collectedPayments: 'Amount collected', awaitingApproval: 'Awaiting approval', thisSeason: 'This season', approvedPayments: 'Approved payments', pendingReserved: 'Reserved amount awaiting approval', transactionHistory: 'Transaction history', transactions: '{{count}} transactions', allPaymentStatuses: 'All statuses', paymentMethod: 'Payment method', amount: 'Amount', date: 'Date', actions: 'Actions', pending: 'Pending', printReceipt: 'Print receipt', noPayments: 'No payments for this season and filter.', recordPayment: 'Record a payment', paymentPendingNotice: 'Payment will be created pending approval.', pilgrimFile: 'Pilgrim application', selectDossier: 'Select an application', selectPackage: 'Select a package', availableBalance: 'Available balance', paymentMethod: 'Payment method', transactionReference: 'Transaction reference (optional)', optionalComment: 'Comment (optional)', savePendingPayment: 'Save as pending', recordPaymentNotice: 'Payment recorded. It is awaiting approval.', paymentApprovedNotice: 'Payment approved. The receipt is now available.', paymentRejectedNotice: 'Payment rejected.', paymentLoadError: 'Unable to load payments. Check the server connection.', invalidDossierPackage: 'Select an application associated with a package.', paymentOverBalance: 'The amount exceeds the available balance of {{amount}}.',
    notificationsTitle: 'Notifications', allNotifications: 'All', unreadNotifications: 'Unread', unreadCount: '{{count}} unread', allCaughtUp: 'You are all caught up', markAllRead: 'Mark all as read', noNotifications: 'No notifications {{filter}}.',
    adminDashboard: 'Dashboard', operationalOverview: 'Operational overview · updated at {{time}}', refresh: 'Refresh', export: 'Export', registeredPilgrimsCard: 'Registered pilgrims', approvedDossiers: 'Approved applications', rejectedDocuments: 'Rejected documents', toVerify: '{{count}} to review', paidTotal: 'Total approved payments', remainingBalance: 'Remaining balance', pilgrimsWithBalance: '{{count}} pilgrims have a balance', registeredDossiers: 'Applications recorded', selectedSeason: 'For the selected season', groupsFormed: 'Groups formed', distributedWithoutGuide: '{{pilgrims}} pilgrims assigned · {{groups}} without a guide', activeGuides: 'Active guides', activeAccounts: 'Active accounts', registrationEvolution: 'Registration activity', currentYearOperations: 'Current year activity · {{season}}', monthlyData: 'Monthly data', dossierStatus: 'Application status', seasonDossiers: '{{count}} applications this season', recentActivity: 'Recent activity', recentOperations: 'Latest recorded operations', filterActivities: 'Filter activities', everything: 'All', noActivityPeriod: 'No activity recorded for this period.', noDossiersRecorded: 'No applications recorded.', noActivityFilter: 'No activity for this filter.', operationalAlerts: 'Operational alerts', followUpPoints: 'Items needing follow-up', noOperationalAlerts: 'No operational alerts.', quickActions: 'Quick actions', commonOperations: 'Shortcuts to common tasks', addPilgrim: 'Add a pilgrim', viewPilgrims: 'View pilgrims', reviewDocuments: 'Review documents', viewApplications: 'View applications', savePayment: 'Record a payment', trackPayments: 'Track collections', sendNotification: 'Send a notification', openInbox: 'Open notifications', seasonPreparation: 'Season preparation', computedProgress: 'Progress calculated from available data', validatedDossiersProgress: 'Approved applications', approvedDocumentsProgress: 'Approved documents', collectedPaymentsProgress: 'Payments collected', groupsWithGuide: 'Groups with a guide',
    profileTitle: 'Account', profileSubtitle: 'Manage your personal information and password.', firstName: 'First name', lastName: 'Last name', currentPassword: 'Current password', newPassword: 'New password', save: 'Save changes', profileSaveSuccess: 'Profile updated successfully.', profileSaveError: 'Unable to update the profile.',
  }),
  fr: Object.freeze({
    dashboard: 'Tableau de bord', overview: "Vue d'ensemble", agencies: 'Agences', dossiers: 'Dossiers', pilgrims: 'Pèlerins', notifications: 'Notifications', payments: 'Paiements', documents: 'Documents', groups: 'Groupes', guides: 'Guides', travel: 'Voyages', presence: 'QR & Présence', statistics: 'Statistiques', organisation: 'Organisation', settings: 'Paramètres', logout: 'Déconnexion', language: 'Langue', welcome: 'Bienvenue', connected: 'Ton compte est connecté au serveur.', myApplications: 'Mes dossiers', noApplications: 'Aucun dossier pour le moment.', loading: 'Chargement…', allApplications: 'Tous les dossiers', allAgencies: 'Toutes les agences', registeredAgencies: 'Agences enregistrées', registeredPilgrims: 'Pèlerins inscrits', activeApplications: 'Dossiers actifs', noData: 'Aucune donnée disponible pour le moment.', search: 'Rechercher', encadreurs: 'Encadreurs', profile: 'Profil', operations: 'Opérations',
    loginKicker: 'Gestion du pèlerinage', loginSubtitle: 'Connecte-toi pour accéder à ton espace.', emailField: 'Email', passwordField: 'Mot de passe', signIn: 'Se connecter', signingIn: 'Connexion…', newPilgrim: 'Nouveau pèlerin ?', createAccount: 'Créer un compte', emailRequired: "L’email est requis.", invalidEmail: 'Format d’email invalide.', passwordRequired: 'Le mot de passe est requis.', invalidCredentials: 'Email ou mot de passe incorrect.', loginError: 'Une erreur est survenue. Réessaie.', registerTitle: 'Créer un compte', registerSubtitle: 'Renseigne tes informations pour démarrer ton dossier.', firstName: 'Prénom', lastName: 'Nom', phone: 'Téléphone', confirmPassword: 'Confirmer le mot de passe', register: 'Créer mon compte', registering: 'Création…', existingAccount: 'Déjà un compte ?', duplicateEmail: 'Cet email est déjà utilisé.', registrationError: 'Impossible de créer le compte.',
    roleAdmin: 'Administrateur', roleAgency: 'Responsable d’agence', roleGuide: 'Guide', rolePilgrim: 'Pèlerin', account: 'Compte', manageAccount: 'Gère tes informations personnelles et ton mot de passe.', currentPassword: 'Mot de passe actuel', newPassword: 'Nouveau mot de passe', saveChanges: 'Enregistrer les modifications', saving: 'Enregistrement…', profileUpdated: 'Profil mis à jour.', profileUpdateFailed: 'Impossible de mettre à jour le profil.',
    pilgrimageManagement: 'Gestion du pèlerinage', allStatus: 'Tous les statuts', noMatchingDossiers: 'Aucun dossier ne correspond aux filtres.', dossier: 'Dossier', pilgrim: 'Pèlerin', agency: 'Agence', createdAt: 'Créé le', documentsProgress: 'Documents', dossierDetails: 'Détails du dossier', dossierHistory: 'Historique du dossier', fullName: 'Nom complet', status: 'Statut', rejectReason: 'Motif du rejet', rejectConfirm: 'Confirmer le rejet', cancel: 'Annuler', validate: 'Valider', reject: 'Rejeter', returnToDossiers: 'Retour aux dossiers', searchDossiers: 'Rechercher par nom ou numéro…', noDossierForAction: 'Aucun dossier à traiter pour le moment.',
    status_brouillon: 'Brouillon', status_soumis: 'Soumis', status_en_verification: 'En vérification', status_valide: 'Validé', status_transmis_nusuk: 'Transmis à Nusuk', status_confirme: 'Confirmé', status_rejete: 'Rejeté', status_annule: 'Annulé',
    statusPending: 'En attente', statusUnderReview: 'En revue', statusApproved: 'Approuvé', statusRejected: 'Rejeté', statusExpired: 'Expiré', statusAll: 'Tous les statuts', statusToReview: 'À traiter', statusNewVersion: 'Nouvelle version requise', reviewFinished: 'Revue terminée', takeForReview: 'Prendre en revue', requestNewVersion: 'Demander une nouvelle version', sendRequest: 'Envoyer la demande', reasonToPilgrim: 'Motif communiqué au pèlerin', searchDocuments: 'Pèlerin, dossier, type ou fichier…', uploadedAt: 'Téléversé le', expiration: 'Expiration', review: 'Revue', noDocumentsForFilter: 'Aucun document pour ce filtre.', documentsToReview: '{{count}} à traiter', documentReviewTitle: 'Documents', documentReviewSubtitle: 'Vérifier les pièces et demander une nouvelle version si nécessaire.',
    season: 'Saison Hajj', createSeason: 'Créer une saison Hajj', newSeason: 'Nouvelle saison', seasonLabel: 'Libellé', seasonYear: 'Année', startDate: 'Date de début', endDate: 'Date de fin', seasonDescription: 'Description', activeSeason: 'Saison active', active: 'Active', inactive: 'Inactive', createPackage: 'Créer un forfait', newPackage: 'Nouveau forfait', packageName: 'Nom du forfait', packageDescription: 'Description', packagePrice: 'Prix', currency: 'Devise', includedServices: 'Prestations incluses', packageActive: 'Forfait actif', seasonsPackages: 'Saisons Hajj & forfaits', seasonTracking: 'Suivi des saisons, forfaits et paiements de la campagne.', noSeasons: 'Aucune saison enregistrée.', noPackages: 'Aucun forfait enregistré.', seasonsCount: 'Saisons', packagesCount: 'Forfaits', paymentCount: 'Paiements', collectedAmount: 'Montant encaissé',
    organisationTitle: 'Organisations', organisationDescription: 'Chaque agence est gérée comme une organisation MyHajj237.', organisationCount: '{{count}} organisation(s)', allOrganisationStatuses: 'Tous les statuts', organisationName: 'Nom de l’organisation', legalName: 'Raison sociale', registrationNumber: 'Numéro d’agrément', country: 'Pays', city: 'Ville', address: 'Adresse', logoUrl: 'URL du logo', subscriptionPlan: 'Formule d’abonnement', subscriptionStatus: 'Statut abonnement', organisationStatus: 'Statut organisation', organisationRecord: 'Enregistrement', contact: 'Contact', subscription: 'Abonnement', edit: 'Modifier', editOrganisation: 'Modifier l’organisation', organisationSaved: 'Organisation mise à jour.', organisationLoadError: 'Impossible de charger les organisations.', noOrganisationMatch: 'Aucune organisation ne correspond à la recherche.', noRegistrationNumber: 'Agrément non renseigné', phoneNotProvided: 'Téléphone non renseigné', close: 'Fermer',
    groupManagementTitle: 'Groupes', groupManagementDescription: 'Créer des groupes, affecter un guide et gérer les pèlerins.', groupCodeName: 'Code / nom', assignedGuide: 'Guide', organisation: 'Organisation', members: 'Pèlerins', manage: 'Gestion', createGroup: 'Créer un groupe', editGroup: 'Modifier le groupe', groupName: 'Nom du groupe', selectOrganisation: 'Sélectionner une organisation', noGuide: 'Aucun guide affecté', guideNotAssigned: 'Guide non affecté', seasonChangeWarning: 'Retire ou déplace les pèlerins avant de changer la saison du groupe.', generatedCode: 'Le code est généré à partir de la saison et de l’identifiant.', groupStats: 'Statistiques des groupes', pilgrimsAssigned: 'Pèlerins répartis', groupAverage: 'Moyenne par groupe', noGroupsSeason: 'Aucun groupe pour cette saison.', groupSaved: 'Groupe enregistré.', groupCreated: 'Groupe créé.', groupUpdated: 'Groupe mis à jour.', groupLoadError: 'Impossible de charger les groupes et les guides.', groupSaveError: 'Impossible d’enregistrer le groupe.', viewPilgrims: 'Pèlerins', selectPilgrim: 'Choisir un pèlerin non affecté', addPilgrim: 'Ajouter un pèlerin', moveTo: 'Déplacer vers', action: 'Action', move: 'Déplacer', remove: 'Retirer', noPilgrimsGroup: 'Aucun pèlerin dans ce groupe.', pilgrimAdded: 'Pèlerin ajouté au groupe.', pilgrimRemoved: 'Pèlerin retiré du groupe.', pilgrimMoved: 'Pèlerin déplacé vers le groupe cible.', addPilgrimError: 'Impossible d’ajouter le pèlerin.', removePilgrimError: 'Impossible de retirer le pèlerin.', movePilgrimError: 'Impossible de déplacer le pèlerin.', loadMembersError: 'Impossible de charger les membres du groupe.',
    chatDiscussion: 'Discussion du groupe', backToGroups: 'Retour aux groupes', noMessages: 'Aucun message. Envoyez la première information au groupe.', writeMessage: 'Écrire un message au groupe…', attachMedia: 'Joindre une photo, vidéo ou PDF', changeMedia: 'Choisir un autre média', removeMedia: 'Retirer le média', mediaPreview: 'Aperçu avant envoi', send: 'Envoyer', sending: 'Envoi…', messageSendError: 'Le message n’a pas pu être envoyé. Réessaie.', messagesLoadError: 'La récupération des messages a échoué.', noGroupAccess: 'Groupe introuvable ou accès refusé.',
    paymentManagement: 'Paiements', paymentSubtitle: 'Encaissements, soldes et validation des règlements Hajj.', registeredPayments: 'Paiements enregistrés', collectedPayments: 'Montant encaissé', awaitingApproval: 'À valider', thisSeason: 'Cette saison', approvedPayments: 'Paiements validés', pendingReserved: 'Montant réservé en attente', transactionHistory: 'Historique des transactions', transactions: '{{count}} transaction(s)', allPaymentStatuses: 'Tous les statuts', paymentMethod: 'Moyen', amount: 'Montant', date: 'Date', actions: 'Actions', pending: 'En attente', printReceipt: 'Imprimer le reçu', noPayments: 'Aucun paiement pour cette saison et ce filtre.', recordPayment: 'Enregistrer un paiement', paymentPendingNotice: 'Le paiement sera créé en attente de validation.', pilgrimFile: 'Dossier pèlerin', selectDossier: 'Sélectionner un dossier', selectPackage: 'Sélectionner un forfait', availableBalance: 'Solde disponible', transactionReference: 'Référence de transaction (facultatif)', optionalComment: 'Commentaire (facultatif)', savePendingPayment: 'Enregistrer en attente', recordPaymentNotice: 'Paiement enregistré. Il est en attente de validation.', paymentApprovedNotice: 'Paiement validé. Le reçu est disponible.', paymentRejectedNotice: 'Paiement rejeté.', paymentLoadError: 'Impossible de charger les paiements. Vérifie la connexion au serveur.', invalidDossierPackage: 'Sélectionne un dossier associé à un forfait.', paymentOverBalance: 'Le montant dépasse le solde disponible de {{amount}}.',
    notificationsTitle: 'Notifications', allNotifications: 'Toutes', unreadNotifications: 'Non lues', unreadCount: '{{count}} non lue(s)', allCaughtUp: 'Tout est à jour', markAllRead: 'Tout marquer comme lu', noNotifications: 'Aucune notification {{filter}}.',
    adminDashboard: 'Tableau de bord', operationalOverview: 'Vue d’ensemble opérationnelle · mise à jour à {{time}}', refresh: 'Actualiser', export: 'Exporter', registeredPilgrimsCard: 'Pèlerins inscrits', approvedDossiers: 'Dossiers validés', rejectedDocuments: 'Documents rejetés', toVerify: '{{count}} à vérifier', paidTotal: 'Total des paiements validés', remainingBalance: 'Solde restant', pilgrimsWithBalance: '{{count}} pèlerins avec un solde', registeredDossiers: 'Dossiers enregistrés', selectedSeason: 'Pour la saison sélectionnée', groupsFormed: 'Groupes formés', distributedWithoutGuide: '{{pilgrims}} pèlerins répartis · {{groups}} sans guide', activeGuides: 'Guides actifs', activeAccounts: 'Comptes actifs enregistrés', registrationEvolution: 'Évolution des inscriptions', currentYearOperations: 'Opérations de l’année en cours · {{season}}', monthlyData: 'Données mensuelles', dossierStatus: 'Statut des dossiers', seasonDossiers: '{{count}} dossiers de la saison', recentActivity: 'Activité récente', recentOperations: 'Dernières opérations enregistrées', filterActivities: 'Filtrer les activités', everything: 'Tout', noActivityPeriod: 'Aucune activité enregistrée pour cette période.', noDossiersRecorded: 'Aucun dossier enregistré.', noActivityFilter: 'Aucune activité pour ce filtre.', operationalAlerts: 'Alertes opérationnelles', followUpPoints: 'Points nécessitant un suivi', noOperationalAlerts: 'Aucune alerte opérationnelle.', quickActions: 'Actions rapides', commonOperations: 'Accès aux opérations courantes', addPilgrim: 'Ajouter un pèlerin', viewPilgrims: 'Consulter les pèlerins', reviewDocuments: 'Valider des documents', viewApplications: 'Voir les dossiers à traiter', savePayment: 'Enregistrer un paiement', trackPayments: 'Suivre les encaissements', sendNotification: 'Envoyer une notification', openInbox: 'Ouvrir la messagerie', seasonPreparation: 'Préparation de la saison', computedProgress: 'Progression calculée sur les données disponibles', validatedDossiersProgress: 'Dossiers validés', approvedDocumentsProgress: 'Documents approuvés', collectedPaymentsProgress: 'Paiements encaissés', groupsWithGuide: 'Groupes avec guide',
  }),
  ar: Object.freeze({
    dashboard: 'لوحة التحكم', overview: 'نظرة عامة', agencies: 'الوكالات', dossiers: 'الملفات', pilgrims: 'الحجاج', notifications: 'الإشعارات', payments: 'المدفوعات', documents: 'الوثائق', groups: 'المجموعات', guides: 'المرشدون', travel: 'الرحلات', presence: 'QR والحضور', statistics: 'الإحصائيات', organisation: 'المنظمة', settings: 'الإعدادات', logout: 'تسجيل الخروج', language: 'اللغة', welcome: 'مرحباً', connected: 'حسابك متصل بالخادم.', myApplications: 'ملفاتي', noApplications: 'لا يوجد ملف حتى الآن.', loading: 'جارٍ التحميل…', allApplications: 'كل الملفات', allAgencies: 'كل الوكالات', registeredAgencies: 'الوكالات المسجلة', registeredPilgrims: 'الحجاج المسجلون', activeApplications: 'الملفات النشطة', noData: 'لا توجد بيانات متاحة حالياً.', search: 'بحث', encadreurs: 'المرشدون', profile: 'الملف الشخصي', operations: 'العمليات',
    loginKicker: 'إدارة الحج', loginSubtitle: 'سجّل الدخول للوصول إلى حسابك.', emailField: 'البريد الإلكتروني', passwordField: 'كلمة المرور', signIn: 'تسجيل الدخول', signingIn: 'جارٍ تسجيل الدخول…', newPilgrim: 'حاج جديد؟', createAccount: 'إنشاء حساب', emailRequired: 'البريد الإلكتروني مطلوب.', invalidEmail: 'أدخل عنوان بريد إلكتروني صالحاً.', passwordRequired: 'كلمة المرور مطلوبة.', invalidCredentials: 'البريد الإلكتروني أو كلمة المرور غير صحيحة.', loginError: 'حدث خطأ. حاول مرة أخرى.', registerTitle: 'إنشاء حساب', registerSubtitle: 'أدخل معلوماتك لبدء ملف الحج.', firstName: 'الاسم الأول', lastName: 'اسم العائلة', phone: 'الهاتف', confirmPassword: 'تأكيد كلمة المرور', register: 'إنشاء حسابي', registering: 'جارٍ الإنشاء…', existingAccount: 'لديك حساب بالفعل؟', duplicateEmail: 'هذا البريد الإلكتروني مستخدم بالفعل.', registrationError: 'تعذر إنشاء الحساب.',
    roleAdmin: 'مسؤول النظام', roleAgency: 'مسؤول الوكالة', roleGuide: 'مرشد', rolePilgrim: 'حاج', account: 'الحساب', manageAccount: 'إدارة معلوماتك الشخصية وكلمة المرور.', currentPassword: 'كلمة المرور الحالية', newPassword: 'كلمة المرور الجديدة', saveChanges: 'حفظ التغييرات', saving: 'جارٍ الحفظ…', profileUpdated: 'تم تحديث الملف الشخصي.', profileUpdateFailed: 'تعذر تحديث الملف الشخصي.',
    pilgrimageManagement: 'إدارة الحج', allStatus: 'كل الحالات', noMatchingDossiers: 'لا توجد ملفات تطابق عوامل التصفية.', dossier: 'الملف', pilgrim: 'الحاج', agency: 'الوكالة', createdAt: 'تاريخ الإنشاء', documentsProgress: 'الوثائق', dossierDetails: 'تفاصيل الملف', dossierHistory: 'سجل الملف', fullName: 'الاسم الكامل', status: 'الحالة', rejectReason: 'سبب الرفض', rejectConfirm: 'تأكيد الرفض', cancel: 'إلغاء', validate: 'اعتماد', reject: 'رفض', returnToDossiers: 'العودة إلى الملفات', searchDossiers: 'البحث بالاسم أو الرقم…', noDossierForAction: 'لا توجد ملفات تحتاج إلى إجراء حالياً.',
    status_brouillon: 'مسودة', status_soumis: 'مُرسل', status_en_verification: 'قيد المراجعة', status_valide: 'معتمد', status_transmis_nusuk: 'أُرسل إلى نسك', status_confirme: 'مؤكد', status_rejete: 'مرفوض', status_annule: 'ملغى',
    statusPending: 'قيد الانتظار', statusUnderReview: 'قيد المراجعة', statusApproved: 'معتمد', statusRejected: 'مرفوض', statusExpired: 'منتهي الصلاحية', statusAll: 'كل الحالات', statusToReview: 'يتطلب المراجعة', statusNewVersion: 'نسخة جديدة مطلوبة', reviewFinished: 'اكتملت المراجعة', takeForReview: 'بدء المراجعة', requestNewVersion: 'طلب نسخة جديدة', sendRequest: 'إرسال الطلب', reasonToPilgrim: 'السبب المرسل للحاج', searchDocuments: 'الحاج أو الملف أو نوع الوثيقة…', uploadedAt: 'تاريخ الرفع', expiration: 'انتهاء الصلاحية', review: 'مراجعة', noDocumentsForFilter: 'لا توجد وثائق تطابق هذا المرشح.', documentsToReview: '{{count}} للمراجعة', documentReviewTitle: 'الوثائق', documentReviewSubtitle: 'راجع الوثائق واطلب نسخة جديدة عند الحاجة.',
    season: 'موسم الحج', createSeason: 'إنشاء موسم حج', newSeason: 'موسم جديد', seasonLabel: 'اسم الموسم', seasonYear: 'السنة', startDate: 'تاريخ البداية', endDate: 'تاريخ النهاية', seasonDescription: 'الوصف', activeSeason: 'موسم نشط', active: 'نشط', inactive: 'غير نشط', createPackage: 'إنشاء باقة', newPackage: 'باقة جديدة', packageName: 'اسم الباقة', packageDescription: 'الوصف', packagePrice: 'السعر', currency: 'العملة', includedServices: 'الخدمات المشمولة', packageActive: 'الباقة نشطة', seasonsPackages: 'مواسم الحج والباقات', seasonTracking: 'متابعة المواسم والباقات ومدفوعات الحملة.', noSeasons: 'لم يتم إنشاء مواسم بعد.', noPackages: 'لم يتم إنشاء باقات بعد.', seasonsCount: 'المواسم', packagesCount: 'الباقات', paymentCount: 'المدفوعات', collectedAmount: 'المبلغ المحصل',
    organisationTitle: 'المنظمات', organisationDescription: 'تُدار كل وكالة كمنظمة على MyHajj237.', organisationCount: '{{count}} منظمة', allOrganisationStatuses: 'كل الحالات', organisationName: 'اسم المنظمة', legalName: 'الاسم القانوني', registrationNumber: 'رقم التسجيل', country: 'البلد', city: 'المدينة', address: 'العنوان', logoUrl: 'رابط الشعار', subscriptionPlan: 'خطة الاشتراك', subscriptionStatus: 'حالة الاشتراك', organisationStatus: 'حالة المنظمة', organisationRecord: 'التسجيل', contact: 'جهة الاتصال', subscription: 'الاشتراك', edit: 'تعديل', editOrganisation: 'تعديل المنظمة', organisationSaved: 'تم تحديث المنظمة.', organisationLoadError: 'تعذر تحميل المنظمات.', noOrganisationMatch: 'لا توجد منظمة تطابق البحث.', noRegistrationNumber: 'رقم التسجيل غير متوفر', phoneNotProvided: 'رقم الهاتف غير متوفر', close: 'إغلاق',
    groupManagementTitle: 'المجموعات', groupManagementDescription: 'أنشئ المجموعات وعيّن مرشداً وأدر الحجاج.', groupCodeName: 'الرمز / الاسم', assignedGuide: 'المرشد', organisation: 'المنظمة', members: 'الحجاج', manage: 'إدارة', createGroup: 'إنشاء مجموعة', editGroup: 'تعديل المجموعة', groupName: 'اسم المجموعة', selectOrganisation: 'اختر منظمة', noGuide: 'لا يوجد مرشد معين', guideNotAssigned: 'المرشد غير معين', seasonChangeWarning: 'أزل الحجاج أو انقلهم قبل تغيير موسم المجموعة.', generatedCode: 'يُنشأ الرمز من الموسم ومعرف المجموعة.', groupStats: 'إحصائيات المجموعات', pilgrimsAssigned: 'الحجاج الموزعون', groupAverage: 'المتوسط لكل مجموعة', noGroupsSeason: 'لا توجد مجموعات لهذا الموسم.', groupSaved: 'تم حفظ المجموعة.', groupCreated: 'تم إنشاء المجموعة.', groupUpdated: 'تم تحديث المجموعة.', groupLoadError: 'تعذر تحميل المجموعات والمرشدين.', groupSaveError: 'تعذر حفظ المجموعة.', viewPilgrims: 'الحجاج', selectPilgrim: 'اختر حاجاً غير معين', addPilgrim: 'إضافة حاج', moveTo: 'النقل إلى', action: 'إجراء', move: 'نقل', remove: 'إزالة', noPilgrimsGroup: 'لا يوجد حجاج في هذه المجموعة.', pilgrimAdded: 'تمت إضافة الحاج إلى المجموعة.', pilgrimRemoved: 'تمت إزالة الحاج من المجموعة.', pilgrimMoved: 'تم نقل الحاج إلى المجموعة المستهدفة.', addPilgrimError: 'تعذرت إضافة الحاج.', removePilgrimError: 'تعذرت إزالة الحاج.', movePilgrimError: 'تعذر نقل الحاج.', loadMembersError: 'تعذر تحميل أعضاء المجموعة.',
    chatDiscussion: 'محادثة المجموعة', backToGroups: 'العودة إلى المجموعات', noMessages: 'لا توجد رسائل بعد. أرسل أول تحديث للمجموعة.', writeMessage: 'اكتب رسالة للمجموعة…', attachMedia: 'إرفاق صورة أو فيديو أو PDF', changeMedia: 'اختيار ملف آخر', removeMedia: 'إزالة الوسيط', mediaPreview: 'معاينة قبل الإرسال', send: 'إرسال', sending: 'جارٍ الإرسال…', messageSendError: 'تعذر إرسال الرسالة. حاول مرة أخرى.', messagesLoadError: 'تعذر جلب الرسائل.', noGroupAccess: 'المجموعة غير موجودة أو لا تملك صلاحية الوصول.',
    paymentManagement: 'المدفوعات', paymentSubtitle: 'التحصيل والأرصدة واعتماد مدفوعات الحج.', registeredPayments: 'المدفوعات المسجلة', collectedPayments: 'المبلغ المحصل', awaitingApproval: 'بانتظار الاعتماد', thisSeason: 'هذا الموسم', approvedPayments: 'المدفوعات المعتمدة', pendingReserved: 'المبلغ المحجوز بانتظار الاعتماد', transactionHistory: 'سجل المعاملات', transactions: '{{count}} معاملة', allPaymentStatuses: 'كل الحالات', paymentMethod: 'الطريقة', amount: 'المبلغ', date: 'التاريخ', actions: 'الإجراءات', pending: 'قيد الانتظار', printReceipt: 'طباعة الإيصال', noPayments: 'لا توجد مدفوعات لهذا الموسم والمرشح.', recordPayment: 'تسجيل دفعة', paymentPendingNotice: 'ستُسجل الدفعة بانتظار الاعتماد.', pilgrimFile: 'ملف الحاج', selectDossier: 'اختر ملفاً', selectPackage: 'اختر باقة', availableBalance: 'الرصيد المتاح', transactionReference: 'مرجع المعاملة (اختياري)', optionalComment: 'تعليق (اختياري)', savePendingPayment: 'حفظ بانتظار الاعتماد', recordPaymentNotice: 'تم تسجيل الدفعة وهي بانتظار الاعتماد.', paymentApprovedNotice: 'تم اعتماد الدفعة. الإيصال متاح الآن.', paymentRejectedNotice: 'تم رفض الدفعة.', paymentLoadError: 'تعذر تحميل المدفوعات. تحقق من اتصال الخادم.', invalidDossierPackage: 'اختر ملفاً مرتبطاً بباقة.', paymentOverBalance: 'المبلغ يتجاوز الرصيد المتاح {{amount}}.',
    notificationsTitle: 'الإشعارات', allNotifications: 'الكل', unreadNotifications: 'غير المقروءة', unreadCount: '{{count}} غير مقروء', allCaughtUp: 'أنت على اطلاع بكل شيء', markAllRead: 'تحديد الكل كمقروء', noNotifications: 'لا توجد إشعارات {{filter}}.',
    adminDashboard: 'لوحة التحكم', operationalOverview: 'نظرة تشغيلية · تم التحديث {{time}}', refresh: 'تحديث', export: 'تصدير', registeredPilgrimsCard: 'الحجاج المسجلون', approvedDossiers: 'الملفات المعتمدة', rejectedDocuments: 'الوثائق المرفوضة', toVerify: '{{count}} للمراجعة', paidTotal: 'إجمالي المدفوعات المعتمدة', remainingBalance: 'الرصيد المتبقي', pilgrimsWithBalance: '{{count}} حاج لديهم رصيد', registeredDossiers: 'الملفات المسجلة', selectedSeason: 'للموسم المحدد', groupsFormed: 'المجموعات المنشأة', distributedWithoutGuide: '{{pilgrims}} حاج موزع · {{groups}} دون مرشد', activeGuides: 'المرشدون النشطون', activeAccounts: 'الحسابات النشطة', registrationEvolution: 'تطور التسجيلات', currentYearOperations: 'أنشطة السنة الحالية · {{season}}', monthlyData: 'بيانات شهرية', dossierStatus: 'حالة الملفات', seasonDossiers: '{{count}} ملف لهذا الموسم', recentActivity: 'النشاط الأخير', recentOperations: 'آخر العمليات المسجلة', filterActivities: 'تصفية الأنشطة', everything: 'الكل', noActivityPeriod: 'لا توجد أنشطة مسجلة لهذه الفترة.', noDossiersRecorded: 'لم يتم تسجيل ملفات.', noActivityFilter: 'لا توجد أنشطة لهذا المرشح.', operationalAlerts: 'تنبيهات تشغيلية', followUpPoints: 'عناصر تتطلب المتابعة', noOperationalAlerts: 'لا توجد تنبيهات تشغيلية.', quickActions: 'إجراءات سريعة', commonOperations: 'اختصارات للعمليات الشائعة', addPilgrim: 'إضافة حاج', viewPilgrims: 'عرض الحجاج', reviewDocuments: 'مراجعة الوثائق', viewApplications: 'عرض الملفات', savePayment: 'تسجيل دفعة', trackPayments: 'متابعة التحصيل', sendNotification: 'إرسال إشعار', openInbox: 'فتح الإشعارات', seasonPreparation: 'الاستعداد للموسم', computedProgress: 'تقدم محسوب من البيانات المتاحة', validatedDossiersProgress: 'الملفات المعتمدة', approvedDocumentsProgress: 'الوثائق المعتمدة', collectedPaymentsProgress: 'المدفوعات المحصلة', groupsWithGuide: 'المجموعات التي لديها مرشد',
    profileTitle: 'الحساب', profileSubtitle: 'إدارة معلوماتك الشخصية وكلمة المرور.', save: 'حفظ التغييرات', profileSaveSuccess: 'تم تحديث الملف الشخصي.', profileSaveError: 'تعذر تحديث الملف الشخصي.',
  }),
});

/** Dictionnaire final : base + chaînes de pages (ces dernières l'emportent). */
export const TRANSLATIONS = Object.freeze(
  Object.fromEntries(Object.keys(BASE_TRANSLATIONS).map((code) => [code, Object.freeze({ ...BASE_TRANSLATIONS[code], ...PAGE_TRANSLATIONS[code], ...OPERATIONS_TRANSLATIONS[code], ...ROLES_TRANSLATIONS[code], ...LIVE_TRANSLATIONS[code], ...MOBILE_TRANSLATIONS[code], ...COURSES_TRANSLATIONS[code], ...PILGRIM_TRANSLATIONS[code] })]))
);

/** Locale Intl par langue (chiffres latins en arabe pour rester cohérent avec les montants). */
export const LOCALES = Object.freeze({ en: 'en-GB', fr: 'fr-FR', ar: 'ar-u-nu-latn' });

/**
 * Traduit une clé avec interpolation `{{nom}}`. Si `values.count` est fourni,
 * la variante `<clé>_one` (count = 1) ou `<clé>_other` est utilisée en priorité.
 */
export function translate(language, key, values = {}) {
  const dictionary = TRANSLATIONS[language] ?? TRANSLATIONS.en;
  let template;
  if (typeof values.count === 'number') {
    const pluralKey = `${key}_${values.count === 1 ? 'one' : 'other'}`;
    template = dictionary[pluralKey] ?? TRANSLATIONS.en[pluralKey];
  }
  template ??= dictionary[key] ?? TRANSLATIONS.en[key] ?? key;
  return Object.entries(values).reduce((text, [name, value]) => text.replaceAll(`{{${name}}}`, String(value)), template);
}
